export const GET_STOCK_SUCCESS = "GET_STOCK_SUCCESS"
export const GET_STOCK_FAILED = "GET_STOCK_FAILED"

export const SEARCH_STOCK_SUCCESS = "SEARCH_STOCK_SUCCESS"
export const SEARCH_STOCK_FAILED = "SEARCH_STOCK_FAILED"

export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS"
export const DELETE_STOCK_FAILED = "DELETE_STOCK_FAILED"